const fs = require('fs');
let c = fs.readFileSync('index (1).html', 'utf-8');
const r = [
  ['Tong lead', 'Tổng lead'],
  ['Lead moi', 'Lead mới'],
  ['Lead chat luong', 'Lead chất lượng'],
  ['Dang ky xet tuyen', 'Đăng ký xét tuyển'],
  ['Nhap hoc', 'Nhập học'],
  ['Ty le chuyen doi', 'Tỷ lệ chuyển đổi'],
  ['Tiep can', 'Tiếp cận'],
  ['Quan tam', 'Quan tâm'],
  ['Dien form', 'Điền form'],
  ['Duoc tu van', 'Được tư vấn'],
  ['Ads / Event / Truong THPT', 'Ads / Event / Trường THPT'],
  ['Click / Mini game / Khao sat', 'Click / Mini game / Khảo sát'],
  ['Dang ky tu van / Xet tuyen', 'Đăng ký tư vấn / Xét tuyển'],
  ['Nhan vien lien he thanh cong', 'Nhân viên liên hệ thành công'],
  ['Da nop ho so chinh thuc', 'Đã nộp hồ sơ chính thức'],
  ['Da dong hoc phi', 'Đã đóng học phí'],
  ['Tuan nay:', 'Tuần này:'],
  ['38.4% vs lead CL', '38.4% vs lead chất lượng'],
  ['49.2% vs dang ky', '49.2% vs đăng ký'],
  ['vs ky truoc', 'vs kỳ trước'],
  ['Su kien truong', 'Sự kiện trường'],
  ['Mien phi', 'Miễn phí'],
  ['Chon nganh nao hop voi ban\\?', 'Chọn ngành nào hợp với bạn?'],
  ['IQ tuyen sinh 2025', 'IQ tuyển sinh 2025'],
  ['Tim truong phu hop', 'Tìm trường phù hợp'],
  ['Cong nghe thong tin', 'Công nghệ thông tin'],
  ['Quan tri kinh doanh', 'Quản trị kinh doanh'],
  ['Dieu duong', 'Điều dưỡng'],
  ['Ke toan', 'Kế toán'],
  ['Thiet ke do hoa', 'Thiết kế đồ họa'],
  ['Duoc hoc', 'Dược học'],
  ['Khac', 'Khác'],
  ['Minh Tu', 'Minh Tú'],
  ['Hong Nhung', 'Hồng Nhung'],
  ['Van Nam', 'Văn Nam'],
  ['Ngoc Anh', 'Ngọc Anh'],
  ['Bao Chau', 'Bảo Châu'],
  ['Co so 1 – Q.Binh Thanh', 'Cơ sở 1 – Q.Bình Thạnh'],
  ['Co so 2 – Q.Tan Binh', 'Cơ sở 2 – Q.Tân Bình'],
  ['Co so 3 – Q.7', 'Cơ sở 3 – Q.7'],
  ['Pheu giao duc – Cao Dang Sai Gon', 'Phễu giáo dục – Cao Đẳng Sài Gòn'],
  ['Theo doi hanh trinh tuyen sinh tu tiep can den nhap hoc', 'Theo dõi hành trình tuyển sinh từ tiếp cận đến nhập học'],
  ['Cap nhat hom nay', 'Cập nhật hôm nay'],
  ['Hom nay', 'Hôm nay'],
  ['Tuan nay', 'Tuần này'],
  ['Thang nay', 'Tháng này'],
  ['Quy nay', 'Quý này'],
  ['Tat ca co so', 'Tất cả cơ sở'],
  ['Tat ca nganh",', 'Tất cả ngành",'],
  ['Tat ca nguon",', 'Tất cả nguồn",'],
  ['Thiet lap chien dich<', 'Thiết lập chiến dịch<'],
  ['Pheu tuyen sinh"', 'Phễu tuyển sinh"'],
  ['highlight diem roi nhieu', 'highlight điểm rơi nhiều'],
  ['% chuyen doi', '% chuyển đổi'],
  ['Canh bao drop-off', 'Cảnh báo drop-off'],
  ['Buoc "Duoc tu van"', 'Bước "Được tư vấn"'],
  ['co ti le roi cao: 52.8% lead khong duoc phan cong kip.', 'có tỉ lệ rơi cao: 52.8% lead không được phân công kịp.'],
  ['Khuyen nghi: Tang lap tuong phan cong tu dong hoac chia se vong Round Robin.', 'Khuyến nghị: Tăng lập tường phân công tự động hoặc chia sẻ vòng Round Robin.'],
  ['Nguon lead"', 'Nguồn lead"'],
  ['Hieu qua thu lead theo kenh – so sanh cost/lead & chuyen doi"', 'Hiệu quả thu lead theo kênh – so sánh cost/lead & chuyển đổi"'],
  ['Phieu khao sat nguyen vong"', 'Phiếu khảo sát nguyện vọng"'],
  ['Cap nhat moi nhat"', 'Cập nhật mới nhất"'],
  ['hoc sinh da dien phieu', 'học sinh đã điền phiếu'],
  ['khao sat → lead', 'khảo sát → lead'],
  ['Top nganh quan tam<', 'Top ngành quan tâm<'],
  ['Mini game tuyen sinh"', 'Mini game tuyển sinh"'],
  ['Hieu qua thu lead theo chien dich game"', 'Hiệu quả thu lead theo chiến dịch game"'],
  ['>Tham gia<', '>Tham gia<'],
  ['Nganh hoc quan tam"', 'Ngành học quan tâm"'],
  ['Phan bo dang ky theo nganh"', 'Phân bổ đăng ký theo ngành"'],
  ['Hieu suat doi tu van"', 'Hiệu suất đội tư vấn"'],
  ['So lead xu ly, ty le chuyen doi va thoi gian phan hoi"', 'Số lead xử lý, tỷ lệ chuyển đổi và thời gian phản hồi"'],
  ['>Tu van vien<', '>Tư vấn viên<'],
  ['>Lead xu ly<', '>Lead xử lý<'],
  ['>Ti le CR<', '>Tỉ lệ CR<'],
  ['>Thoi gian PH<', '>Thời gian PH<'],
  ['Hieu suat theo co so"', 'Hiệu suất theo cơ sở"'],
  ['So sanh so lead va nhap hoc – ti le chuyen doi"', 'So sánh số lead và nhập học – tỉ lệ chuyển đổi"'],
  ['Pheu tra gop — Di Dong Viet', 'Phễu trả góp — Di Động Việt'],
  ['Phan tich hanh trinh khach hang tra gop', 'Phân tích hành trình khách hàng trả góp'],
  ['Tat ca chi nhanh",', 'Tất cả chi nhánh",'],
  ['>Quan 1<', '>Quận 1<'],
  ['>Quan 7<', '>Quận 7<'],
  ['>Thu Duc<', '>Thủ Đức<'],
  ['Tat ca kenh",', 'Tất cả kênh",'],
  ['>Cua hang<', '>Cửa hàng<'],
  ['Xuat bao cao<', 'Xuất báo cáo<'],
  ['Pheu chuyen doi tra gop"', 'Phễu chuyển đổi trả góp"'],
  ['Hanh trinh khach hang tu tiep can den mua tra gop"', 'Hành trình khách hàng từ tiếp cận đến mua trả góp"'],
  ['Hinh thuc tra gop"', 'Hình thức trả góp"'],
  ['Phan bo theo loai the tin dung"', 'Phân bổ theo loại thẻ tín dụng"'],
  ['>giao dich<', '>giao dịch<'],
  ['Top san pham mua tra gop"', 'Top sản phẩm mua trả góp"'],
  ['San pham co luot tra gop cao nhat"', 'Sản phẩm có lượt trả góp cao nhất"'],
  ['>San pham<', '>Sản phẩm<'],
  ['>So luong<', '>Số lượng<'],
  ['>TB gia tri<', '>TB giá trị<'],
  ['>Tang truong<', '>Tăng trưởng<'],
  ['Kenh mang lai khach tra gop"', 'Kênh mang lại khách trả góp"'],
  ['So lead va ty le chuyen doi tung kenh"', 'Số lead và tỷ lệ chuyển đổi từng kênh"'],
  ['Hieu suat chi nhanh"', 'Hiệu suất chi nhánh"'],
  ['Top cua hang co nhieu giao dich tra gop nhat"', 'Top cửa hàng có nhiều giao dịch trả góp nhất"'],
  ['>Giao dich<', '>Giao dịch<'],
  ['>Doanh thu<', '>Doanh thu<'],
  ['>Hieu suat<', '>Hiệu suất<'],
  ['>Tai cua hang<', '>Tại cửa hàng<'],
  ['>Quan 1 – Nguyen Trai<', '>Quận 1 – Nguyễn Trãi<'],
  ['>Quan 7 – Nguyen Huu Tho<', '>Quận 7 – Nguyễn Hữu Thọ<'],
  ['>Thu Duc – Vo Van Ngan<', '>Thủ Đức – Võ Văn Ngân<'],
  ['>Binh Thanh – Xo Viet<', '>Bình Thạnh – Xô Viết<'],
  ['>Tan Binh – Cong Hoa<', '>Tân Bình – Cộng Hòa<'],
  ['>Quan 3 – Vo Van Tan<', '>Quận 3 – Võ Văn Tần<']
];
r.forEach(p => {
  c = c.replace(new RegExp(p[0], 'g'), p[1]);
});
fs.writeFileSync('index (1).html', c);
console.log('Modified successfully.');
